# Generated by Django 4.2 on 2025-07-08 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksManage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(max_length=140, verbose_name='著者'),
        ),
        migrations.AlterField(
            model_name='article',
            name='isbn',
            field=models.CharField(max_length=140, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='article',
            name='lang',
            field=models.CharField(max_length=140, verbose_name='言語'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='開始日'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publisher',
            field=models.CharField(max_length=140, verbose_name='出版社'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=140, verbose_name='タイトル'),
        ),
    ]
