# Generated by Django 4.2 on 2025-07-08 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksManage', '0002_alter_article_author_alter_article_isbn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=140, verbose_name='ISBN')),
                ('title', models.CharField(max_length=140, verbose_name='タイトル')),
                ('author', models.CharField(max_length=140, verbose_name='著者')),
                ('info', models.CharField(max_length=140, verbose_name='あらすじ')),
                ('publisher', models.CharField(max_length=140, verbose_name='出版社')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='開始日')),
                ('genre', models.CharField(max_length=140, verbose_name='ジャンル')),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
