# Generated by Django 4.2 on 2025-07-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksManage', '0003_books_delete_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='出版日'),
        ),
        migrations.AlterModelTable(
            name='books',
            table='books',
        ),
    ]
