# Generated by Django 4.2 on 2025-07-11 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booksManage', '0004_alter_books_published_date_alter_books_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='info',
        ),
    ]
