# Generated by Django 4.2 on 2025-07-18 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksManage', '0005_remove_books_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='rent',
            field=models.BooleanField(default=False, verbose_name='貸出状況'),
        ),
    ]
