# Generated by Django 4.2 on 2025-08-01 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booksManage', '0006_books_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='rent_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='貸出ユーザー'),
        ),
    ]
